version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev  # Specify the development Dockerfile
    container_name: FARM-frontned-dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    env_file:
      - ./frontend/.env.development
    networks:
      - mynetwork
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev  # Specify the development Dockerfile
    container_name: FARM-backend-dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env.development
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  node_modules: