version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev  # Ensure this Dockerfile is tailored for the frontend
    container_name: FARM-frontend-dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - node_modules_frontend:/app/node_modules  # Named volume for frontend node_modules
    env_file:
      - ./frontend/.env.development
    networks:
      - mynetwork
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev  # Ensure this Dockerfile is tailored for FastAPI backend
    container_name: FARM-backend-dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - node_modules_backend:/app/node_modules  # Named volume for backend node_modules
    env_file:
      - ./backend/.env.development
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  node_modules_frontend:  # Named volume for frontend node_modules
  node_modules_backend:  # Named volume for backend node_modules
