version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev  # Specify the development Dockerfile
    container_name: FARM-dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  node_modules: