version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev  # Specify the development Dockerfile
    container_name: reactworkflow-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - mynetwork

networks:
  mynetwork: