version: '3.4'

services:
  reactworkflow-prod:
    image: reactworkflow-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - .env.production
    ports:
      - 3000:3000
