version: '3.4'

services:
  reactworkflow-dev:
    image: reactworkflow-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env.development
    ports:
      - 3000:3000