# Stage 1: Build the application
FROM node:lts-alpine AS build

# Set working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY ["package.json", "package-lock.json*", "./"]

# Install all dependencies (including dev dependencies)
RUN npm install --silent

# Copy the rest of the application code
COPY . .

CMD ["npm", "run", "dev"]
